[2025-04-09T07:28:18.647+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline_modo_prueba.export_to_csv manual__2025-04-09T07:27:59.723185+00:00 [queued]>
[2025-04-09T07:28:18.658+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline_modo_prueba.export_to_csv manual__2025-04-09T07:27:59.723185+00:00 [queued]>
[2025-04-09T07:28:18.659+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-04-09T07:28:18.704+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): export_to_csv> on 2025-04-09 07:27:59.723185+00:00
[2025-04-09T07:28:18.710+0000] {standard_task_runner.py:60} INFO - Started process 148 to run task
[2025-04-09T07:28:18.713+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline_modo_prueba', 'export_to_csv', 'manual__2025-04-09T07:27:59.723185+00:00', '--job-id', '96', '--raw', '--subdir', 'DAGS_FOLDER/etl_workflow.py', '--cfg-path', '/tmp/tmp4ze4njyf']
[2025-04-09T07:28:18.715+0000] {standard_task_runner.py:88} INFO - Job 96: Subtask export_to_csv
[2025-04-09T07:28:18.792+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_pipeline_modo_prueba.export_to_csv manual__2025-04-09T07:27:59.723185+00:00 [running]> on host d9666b3d8245
[2025-04-09T07:28:18.967+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='simon' AIRFLOW_CTX_DAG_ID='etl_pipeline_modo_prueba' AIRFLOW_CTX_TASK_ID='export_to_csv' AIRFLOW_CTX_EXECUTION_DATE='2025-04-09T07:27:59.723185+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-09T07:27:59.723185+00:00'
[2025-04-09T07:28:18.968+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-09T07:28:18.969+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/***/scripts/export_to_csv.py']
[2025-04-09T07:28:18.982+0000] {subprocess.py:86} INFO - Output:
[2025-04-09T07:28:19.525+0000] {subprocess.py:93} INFO - ‚ùå Error al exportar a CSV: [Errno 2] No such file or directory: '../data/processed/final_merged.parquet'
[2025-04-09T07:28:19.631+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-04-09T07:28:19.685+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=etl_pipeline_modo_prueba, task_id=export_to_csv, execution_date=20250409T072759, start_date=20250409T072818, end_date=20250409T072819
[2025-04-09T07:28:19.809+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-04-09T07:28:19.827+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
