[2025-04-09T18:28:47.830+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline_modo_prueba.export_to_csv manual__2025-04-09T18:21:44.490977+00:00 [queued]>
[2025-04-09T18:28:47.842+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline_modo_prueba.export_to_csv manual__2025-04-09T18:21:44.490977+00:00 [queued]>
[2025-04-09T18:28:47.842+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-04-09T18:28:47.891+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): export_to_csv> on 2025-04-09 18:21:44.490977+00:00
[2025-04-09T18:28:47.897+0000] {standard_task_runner.py:60} INFO - Started process 204 to run task
[2025-04-09T18:28:47.900+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline_modo_prueba', 'export_to_csv', 'manual__2025-04-09T18:21:44.490977+00:00', '--job-id', '154', '--raw', '--subdir', 'DAGS_FOLDER/etl_workflow.py', '--cfg-path', '/tmp/tmpohjyepd0']
[2025-04-09T18:28:47.902+0000] {standard_task_runner.py:88} INFO - Job 154: Subtask export_to_csv
[2025-04-09T18:28:47.991+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_pipeline_modo_prueba.export_to_csv manual__2025-04-09T18:21:44.490977+00:00 [running]> on host 771ae2283d18
[2025-04-09T18:28:48.167+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='simon' AIRFLOW_CTX_DAG_ID='etl_pipeline_modo_prueba' AIRFLOW_CTX_TASK_ID='export_to_csv' AIRFLOW_CTX_EXECUTION_DATE='2025-04-09T18:21:44.490977+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-09T18:21:44.490977+00:00'
[2025-04-09T18:28:48.168+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-09T18:28:48.169+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/***/scripts/export_to_csv.py']
[2025-04-09T18:28:48.183+0000] {subprocess.py:86} INFO - Output:
[2025-04-09T18:28:48.651+0000] {subprocess.py:93} INFO - ‚ùå Error al exportar a CSV: [Errno 2] No such file or directory: '/opt/***/data/processed/final_merged.parquet'
[2025-04-09T18:28:48.746+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-04-09T18:28:48.806+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=etl_pipeline_modo_prueba, task_id=export_to_csv, execution_date=20250409T182144, start_date=20250409T182847, end_date=20250409T182848
[2025-04-09T18:28:48.875+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-04-09T18:28:48.894+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
