[2025-04-09T07:11:19.982+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline_modo_prueba.transform_grammy manual__2025-04-09T07:11:12.014769+00:00 [queued]>
[2025-04-09T07:11:19.992+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline_modo_prueba.transform_grammy manual__2025-04-09T07:11:12.014769+00:00 [queued]>
[2025-04-09T07:11:19.993+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-04-09T07:11:20.092+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): transform_grammy> on 2025-04-09 07:11:12.014769+00:00
[2025-04-09T07:11:20.099+0000] {standard_task_runner.py:60} INFO - Started process 134 to run task
[2025-04-09T07:11:20.103+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline_modo_prueba', 'transform_grammy', 'manual__2025-04-09T07:11:12.014769+00:00', '--job-id', '82', '--raw', '--subdir', 'DAGS_FOLDER/etl_workflow.py', '--cfg-path', '/tmp/tmp0r_ko87i']
[2025-04-09T07:11:20.105+0000] {standard_task_runner.py:88} INFO - Job 82: Subtask transform_grammy
[2025-04-09T07:11:20.205+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_pipeline_modo_prueba.transform_grammy manual__2025-04-09T07:11:12.014769+00:00 [running]> on host 6d74a53745cf
[2025-04-09T07:11:20.376+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='simon' AIRFLOW_CTX_DAG_ID='etl_pipeline_modo_prueba' AIRFLOW_CTX_TASK_ID='transform_grammy' AIRFLOW_CTX_EXECUTION_DATE='2025-04-09T07:11:12.014769+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-09T07:11:12.014769+00:00'
[2025-04-09T07:11:20.379+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-09T07:11:20.380+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/***/scripts/transform_grammy.py']
[2025-04-09T07:11:20.398+0000] {subprocess.py:86} INFO - Output:
[2025-04-09T07:11:24.541+0000] {subprocess.py:93} INFO - ‚ùå Error al transformar Grammy: [Errno 2] No such file or directory: '../data/processed/grammy.parquet'
[2025-04-09T07:11:24.662+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-04-09T07:11:24.735+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=etl_pipeline_modo_prueba, task_id=transform_grammy, execution_date=20250409T071112, start_date=20250409T071119, end_date=20250409T071124
[2025-04-09T07:11:24.859+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-04-09T07:11:24.905+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
